import Intro from '@/components/Intro'
import NavBar from '@/components/NavBar'
import Head from 'next/head'
import { useDispatch } from 'react-redux'
import { setUserToken, setUserData } from '@/Utils/UserSlice'
import { useEffect } from 'react'
import Cookies from 'js-cookie'
import useSWR from 'swr'
import { get_job } from '@/Services/job'
import { setJobData } from '@/Utils/JobSlice'
import { RevolvingDot } from 'react-loader-spinner'

export default function Home() {
  const dispatch = useDispatch();
  const { data, error, isLoading } = useSWR('/getAllJobs', get_job)
  useEffect(() => {
    if (data) dispatch(setJobData(data?.data))
  }, [data, dispatch])

  return (
    <>

      <Head>
        <title>QuickHire</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      {
        isLoading ? (
          <div className='bg-gray w-full h-screen flex items-center flex-col justify-center'>
            <RevolvingDot width='200' color="#808080" />
            <p className='text-xs uppercase'>Loading ...</p>
          </div>
        ) : (
          <>
            <NavBar />
            <div className="w-full h-screen bg-gray-200  text-black">
              <Intro />
            </div>
          </>
        )
      }
    </>
  )
}
